# Site settings
title: TYSEC
description: "Proteção"
baseurl: "" # for test: remove string '/rsrs' to ''
url: "http://tysec.github.io/" 
# User settings
username: TySec
user_title: TySec - FrontEnd
email: tyseccorporate@gmail.com
github_username:  tesec
profile_picture: http://i.imgur.com/vgQnHIn.jpg
# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: Inicio
    url: /
  - title: Postagem
    url: /posts
  - title: Outros
    url: /Outros
  - title: TEsec
    url: /TEsec
  - title: Sobre
    url: /Sobre
 
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
