# Site settings
title: TEsec 
description: "Aprendizagem..."
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "http://tesec.github.io/" 
# User settings
username: TEsec
user_title: TEsec - FrontEnd
email: tesec111@hotmail.com
twitter_username: tesec
github_username:  tesec
gplus_username:  tesec
disqus_username: tesec
profile_picture: 
# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: Inicio
    url: /
  - title: Postagem
    url: /posts
  - title: Outros
    url: /Outros
  - title: TEsec
    url: /TEsec
  - title: Sobre
    url: /Sobre
 
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
