# Site settings
title: TEsec 
description: "Aprendizagem..."
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "http://tesec.github.io/" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'
# User settings
username: Thyago
user_title: TEsec - FrontEnd
email: lorem.lorem@ipsum.com
twitter_username: tesec
github_username:  tesec
gplus_username:  tesec
disqus_username: tesec
profile_picture: https://68.media.tumblr.com/93f384858e9273d5b980b418e2f2f4d5/tumblr_o5i2aybLJG1uapsfmo2_250.png

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: Inicio
    url: /
  - title: Postagem
    url: /posts
  - title: Outros
    url: /outros
  - title: TEsec
    url: /tags
  - title: Sobre
    url: /sobre
 
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
